### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by thecodechaser** [thecodechaser/space-travelers-hub#25]
## This issue includes the following details for the review:
- For this react-redux group project, We are only two members in the teams @thecodechaser, @KayLemba 
-  We removed all cards with title Team3 from the Kanban board
-  We closed all issues with titleTeam3

Link to the Github project (Kanban board): [Github project](https://github.com/thecodechaser/space-travelers-hub/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @thecodechaser and @KayLemba,

Your Kanban board is well set up and cards are correctly assigned. Your project is complete! :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
